### ISSUE TITLE
Binding hotkeys?

### ISSUE THREAD

**Issue by af** [tylergaw/js-osx-app-examples#1]
Hi, thanks for your work on documenting how to build JavaScript for Automation apps. Your blogpost and examples are by far the best resources I've found so far.

I'm wondering if you know of any way to bind to keystroke events using JS for Automation? Ideally I'd like to respond to global keyboard events (ie. when the app is not focused), but I'm not sure if that's possible. Through searching around, it seems like an old Carbon API called `RegisterEventHotKey` is the way most OS X apps do this. It looks like you can import and use these APIs, my WIP attempt looks something like:

```
ObjC.import("Cocoa")
ObjC.import("Carbon")
var hotkeyHandler = function(evt) { $.NSLog('hello from handler') }
var evtType = { eventClass: $.kEventClassKeyboard, eventKind: $.kEventHotKeyPressed }
var keyCodeForV = 9

$.InstallEventHandler($.GetApplicationEventTarget(), hotkeyHandler, 1, evtType, {}, null)
s = $.RegisterEventHotKey(keyCodeForV, ($.controlKey | $.cmdKey), {id: 1, signature: 'asdf'}, $.GetApplicationEventTarget(), 0, {});
```

This doesn't work, but running each of the Carbon functions/variables through console.log shows that they are available and ready to use. The arguments that are empty object literals are the ones I'm unclear about.

The following links look useful for figuring this out, and looking at the Carbon header file at `/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Headers/Events.h` has also been helpful:
http://stackoverflow.com/questions/8201338/how-to-implement-shortcut-key-input-in-mac-cocoa-app
http://dbachrach.com/blog/2005/11/program-global-hotkeys-in-cocoa-easily/
http://snippets.aktagon.com/snippets/361-registering-global-hot-keys-with-cocoa-and-objective-c

Not sure if an issue is the best way to ask this, but thought it might be useful to others as well if it was documented here. Any pointers or tips would be appreciated!

**Comment by tylergaw** [comment]
Thanks @af. Yep, this is a great way to ask. I haven't done any work with hotkeys so I don't know off hand. I'm going to try out your sample code/read those articles and see if I can get it working.

An initial search landed me on https://github.com/shpakovski/MASShortcut, but I'd like to see If we can get the Carbon event stuff working before trying the MAS route. Mostly just because I'm curious as to why it isn't working.

I'll let you know what I find.

**Comment by af** [comment]
@tylergaw Great! Looking forward to seeing what you can figure out. I have zero experience with native development on OS X so I was a bit out of my depth in trying to get this going. Being able to bind global hotkeys with js would be pretty great though!

**Comment by af** [comment]
Just found this old issue– if anyone's interested in custom keybindings on OS X, [hammerspoon](http://hammerspoon.org) is what I'm using and it works great
